apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: starswar

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/cilium/cilium/1.16.1/examples/minikube/http-sw-app.yaml
  - route.yml