apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  # Gateway API
  # standard CRD
  # - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
  # experiment CRD
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml
  # cilium powered gateway
  - gateway.yml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yml