operator:
  replicas: 3
  # Observability with signoz
  podAnnotations:
    signoz.io/scrape: 'true'
    signoz.io/port: '9963'
    signoz.io/path: /metrics


hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# IP management
ipam:
  mode: kubernetes

# Gateway API controller
# either enable kubeProxyReplacement or nodePort 
# kubeProxyReplacement: true
nodePort:
  enabled: true

l7Proxy: true

# Observability with signoz
# Expose metrics
prometheus:
  enabled: true

podAnnotations:
  signoz.io/scrape: 'true'
  signoz.io/port: '9962'
  signoz.io/path: /metrics

envoy:
  podAnnotations:
    signoz.io/scrape: 'true'
    signoz.io/port: '9964'
    signoz.io/path: /metrics

# Gateway API & Ingress controller
gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true
    nodes:
      matchLabels:
        hostNetwork: "true"

  gatewayClass:
    create: "true"

# ingressController:
#   enabled: true
#   loadbalancerMode: shared
#   service:
#     insecureNodePort: 31799
#     secureNodePort: 32426